config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "characters#index"

  resources :characters do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:index, :new, :create]
  end
  resources :bookings, only: [:edit, :update, :destroy]
  get "/dashboard", to: "bookings#index", as: :dashboard
  patch "/bookings/:id/accept", to: "bookings#accept", as: :accept
  patch "/bookings/:id/decline", to: "bookings#decline", as: :decline
  get "/mycharacters", to: "characters#mychars", as: :mychars

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :character

  validates :start_date, :end_date, presence: true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews, dependent: :destroy
  has_one_attached :photo

  validates :name, :location, :price, presence: true
  validates :name, uniqueness: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  def rating
    self.reviews.sum { |r| r.reco? ? 1 : -1  }
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :character

  validates :content, presence: true
  validates :reco, inclusion: {in: [true, false]}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :characters
  has_many :reviews

  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_character, only: %i[create new]
  before_action :set_booking, except: %i[new create index]

  def index
    @bookings = Booking.where(user: current_user)
    @my_bookings = Booking.where(character_id: current_user.characters)
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(params_booking)
    @booking.character = @character
    @booking.user = current_user
    if @booking.save
      redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @booking.update(params_booking) if @booking.character.user == current_user
    redirect_to booking_path(@booking)
  end

  def destroy
    @booking.destroy
    redirect_to dashboard_path
  end

  def accept
    @booking.update(status: true)
    redirect_to dashboard_path
  end

  def decline
    @booking.update(status: false)
    redirect_to dashboard_path
  end

  private

  def set_character
    @character = Character.find(params[:character_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def params_booking
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :destroy, :edit, :update]

  def index
    @characters = Character.with_attached_photo.includes(:reviews).all
    @reviews = Review.order("RANDOM()").limit(3)

    if params[:query].present?
      sql_subquery = "name ILIKE :query OR univers ILIKE :query"
      @characters = @characters.where(sql_subquery, query: "%#{params[:query]}%")
    end

    sort_order = params[:desc] ? :desc : params[:asc] ? :asc : nil
    @characters.order(price: sort_order) if sort_order

    @markers = @characters.geocoded.map do |character|
      {
        lat: character.latitude,
        lng: character.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { character: character })
      }
    end

    if params[:r_asc].present?
      @characters = @characters.sort_by(&:rating)
      # @characters = @characters.sort_by { |character| character.rating }
    elsif params[:r_desc].present?
      @characters = @characters.sort_by(&:rating).reverse
    end

  end


  def new
    @character = Character.new
  end

  def show
    @review = Review.new
  end

  def create
    @character = Character.new(params_character)
    @character.user = current_user
    if @character.save
      redirect_to character_path(@character)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @character.update(params_character) if @character.user == current_user
    redirect_to character_path(@character)
  end

  def destroy
    @character.destroy if @character.user == current_user
    redirect_to characters_path, status: :see_other
  end

  def mychars
    @characters = Character.where(user: current_user)
  end

  private

  def set_character
    @character = Character.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def params_character
    params.require(:character).permit(:name, :location, :univers, :price, :skills, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_character, only: %i[new create]

  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.character = @character
    @review.user = current_user
    @review.save
    if @review.save
      redirect_to character_path(@character)
    else
      @review_modal_open = true
      render 'characters/show', status: :unprocessable_entity
    end
  end

  private

  def set_character
    @character = Character.find(params[:character_id])
  end

  def set_reviews
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:content, :reco)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div data-controller="booking" data-booking-price-value="<%= @character.price %>" >
  <%= simple_form_for [character, booking] do |f| %>
    <div class="d-flex">
    <%= f.input :start_date,
      as: :string,
      input_html: { data: { controller: "datepicker", action: "change->booking#update", datepicker_target: 'start_date', booking_target: "start_date" }, min: Date.today } %>

    <%= f.input :end_date,
      as: :string,
      input_html: { data: { controller: "datepicker", action: "change->booking#update", datepicker_target: 'end_Date', booking_target: "end_date" }, min: Date.today } %>
    </div>
    <div class="border rounded p-4">
      <div class="form-group">
        <strong>Price per day :</strong>
        <span id="price-per-day"><%= @character.price %> $</span>
      </div>
      <div>
        <strong>Details :</strong><br>
        <span data-booking-target='info'></span>
        <div class="border-top pt-3" >
          <strong>Total price :</strong>
          <span data-booking-target="price"></span><br>
        </div>
      </div>
    </div>
    <div class="text-center">
      <%= f.submit 'Book a hero', class:"btn btn-ghost-pink my-3" %>
    </div>

  <% end %>
</div>

app/views/bookings/index.html.erb
<h1>Hello <%= current_user.first_name %></h1>

<div class="container mt-5">
    <div class="row d-flex">
        <!-- My Characters' Bookings -->
        <div class="col-md-6 mb-4">
            <div class="p-3 border rounded-4 equal-height shadow"">
                <h4 class="text-center mb-3">My characters' bookings</h4>
                <ul class="list-group">
                    <% @my_bookings.each do |booking| %>
                        <% if booking.character.user == current_user %>
                            <li class="d-flex list-group-item" data-controller="booking" data-booking-price-value="<%= booking.character.price %>">
                              <div class="card big_img">
                                <% if booking.character.photo.attached? == true %>
                                  <%= cl_image_tag booking.character.photo.key, alt: "text" %>
                                <% else %>
                                  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" alt="<%= @character[:name] %>">
                                <% end %>
                              </div>
                              <div>
                                <p class="m-3"><%= "#{booking.user.first_name} wants" %> <%= link_to booking.character.name, character_path(booking.character) %><br>
                                <span data-booking-target="info"></span> =
                                <span data-booking-target="price"></span>
                                <p class="m-3">From:
                                <span data-booking-action="change->booking#updatedash" data-booking-target="start_date"><%= booking.start_date %></span><br>
                                to:
                                <span data-booking-action="change->booking#updatedash" data-booking-target="end_date"><%= booking.end_date %></span>
                                </p>
                                </p>
                                <% if booking.status == nil %>
                                    <p class="centered">
                                        <%= link_to "✓", accept_path(booking), data: {turbo_method: :patch, turbo_confirm: "Are you sure you want to accept this booking?"}, class: "btn btn-accept" %>
                                        <%= link_to "✕", decline_path(booking), data: {turbo_method: :patch, turbo_confirm: "Are you sure you want to decline this booking?"}, class: "btn btn-decline" %>
                                    </p>
                                <% elsif booking.status == true %>
                                    <p class="accept centered"><b>Accepted</b> <span class="px-2">✓</span></p>
                                <% else %>
                                    <p class="decline centered"><b>Declined</b> <span class="px-2">✕</span></p>
                                <% end %>
                              </div>
                            </li>
                        <% end %>
                    <% end %>
                </ul>
            </div>
        </div>

        <!-- My Bookings -->
        <div class="col-md-6 mb-4">
            <div class="p-3 border rounded-4 equal-height shadow">
                <h4 class="text-center mb-3">My bookings</h4>
                <ul class="list-group">
                    <% @bookings.each do |booking| %>
                        <% if booking.user == current_user %>
                            <li class="d-flex list-group-item" data-controller="booking" data-booking-price-value="<%= booking.character.price %>">
                              <div class="card big_img">
                                <% if booking.character.photo.attached? == true %>
                                  <%= cl_image_tag booking.character.photo.key, alt: "text" %>
                                <% else %>
                                  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" alt="<%= @character[:name] %>">
                                <% end %>
                              </div>
                              <div>
                                <p class="m-3">
                                <%= link_to booking.character.name, character_path(booking.character) %><br>
                                <span data-booking-target="info""></span> =
                                <span data-booking-target="price"></span>
                                <p class="m-3">From:
                                <span data-booking-action="change->booking#updatedash" data-booking-target="start_date"><%= booking.start_date %></span><br>
                                to:
                                <span data-booking-action="change->booking#updatedash" data-booking-target="end_date"><%= booking.end_date %></span>
                                </p>
                                </p>
                                <% if booking.status %>
                                    <p class="accept centered"><b>Accepted</b><span class="px-2">✓</span></p>
                                <% elsif booking.status == nil %>
                                    <p class="pending centered"><b>Pending</b> <span class="px-2"><i class="fa-solid fa-clock"></i></span></p>
                                <% else %>
                                    <p class="decline centered"><b>Declined</b> <span class="px-2">✕</span></p>
                                <% end %>
                                </div>
                            </li>
                        <% end %>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="mx-auto my-5">
    <%= link_to "Back to list", characters_path, class: "btn btn-large" %>
</div>

app/views/bookings/new.html.erb
<div class="container">
<div class="row">
  <div class="col-6 mx-auto">

    <h1>New booking</h1>

      <p>Do you want to book <%= @character[:name] %> ?</p>
      <%= render "form", booking: @booking, character: @character %>

    </div>
  </div>
</div>

app/views/characters/_form.html.erb
<div class="mb-3">
<%= simple_form_for(character) do |f| %>
  <%= f.input :name %>
  <%= f.input :location %>
  <%= f.input :univers, label: "Universe" %>
  <%= f.input :price %>
  <%= f.input :skills %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Submit", class: "btn-ghost btn-ghost:hover" %>
<% end %>
</div>

app/views/characters/_form_filters.html.erb
<%# <%= simple_form_for(characters) do |f| %>
  <%# <%= f.input :price, as: :select, prompt: 'Choose a price', collection: ['1-100$', '101-300$', '301-600$', '601-1000$', '1000 and beyond'] %>
  <%# <%= f.input :skills, as: :select, prompt: 'Choose a skill', collection: ['Problem solving', 'Hooping', 'Networking skills'] %>
  <%# <%= f.submit "Search", class: "btn-ghost btn-ghost:hover" %>
<%# <% end %>

<%# <%= form_with url: characters_path, method: :get do |f| %>
  <%# <%= select_tag :price, options_for_select([['prix asc', '1'], ['prix desc', '2']]), { prompt: "Choose a price", selected: '2' } %>
  <%# <%= f.submit "toto" %>
<%# <% end %>

<%= form_with url: characters_path, method: :get, class: "d-flex" do |f| %>
  <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find your favorite character"
  %>
  <span class="ms-3"><%= submit_tag "Search", name: "", class: "btn btn-ghost" %></span>
<% end %>

app/views/characters/_info_window.html.erb
<div class= "mapboxlabel">
  <%= link_to character_path(character) do %>
  <div class= "d-flex gap-2">
    <%= cl_image_tag character.photo.key, alt: "text", height: 50, width: 50, class: "rounded-circle object-fit-cover" %>
    <div>
      <h6><%= character.name %></h6>
      <p><%= character.location %></p>
    </div>
  </div>
  <% end %>
</div>

app/views/characters/_modal.html.erb
<div class="modal fade" id="editcharacter" tabindex="-1" role="dialog" aria-labelledby="editcharacterLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editcharacterLabel"><%= @character.name %></h5>
      </div>
      <div class="modal-body">
        <%= render "characters/form", character: @character %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="addreview" tabindex="-1" role="dialog" aria-labelledby="addreviewLabel" aria-hidden="true"
  data-controller="modal"
  data-modal-open-value="<%= !!open %>">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addreviewLabel"><%= @character.name %></h5>
      </div>
      <div class="modal-body">
        <%= render "reviews/form", review: review, user: @user, character: @character %>
      </div>
    </div>
  </div>
</div>

app/views/characters/edit.html.erb
<div class="col-4 mx-auto">

  <% if @character.user == current_user %>
    <h1 class="my-5">Edit your character</h1>
  <% else %>
    <h1 class="my-5">Book your character</h1>
  <% end %>

  <%= render 'form', character: @character %>

</div>

app/views/characters/index.html.erb
<div class="banner">
  <div class="container">
    <h1 class="fs-1 mb-3">MythicMates</h1>
    <div class="d-flex flex-column align-items-center">
      <p class="mb-5">Who do you feel like today?</p>
      <a href="#browse" class="btn btn-ghost mt-5" >Browse</a>
    </div>
  </div>
</div>

<div class="text-white" id="filteranchor">
  <p>anchor</p>
</div>

<div class="mx-5 mt-5 mb-3" id="browse">
  <%= render 'form_filters' %>
</div>

<div class="d-flex justify-content-start align-items-center mb-3 mx-5">
  <p class="mt-3 mx-3">Sort by:</p>
  <%= link_to "Best reviews", characters_path(r_asc: true, anchor:"filteranchor"), class: "btn btn-filters" %>
  <%= link_to "Worst reviews", characters_path(r_desc: true, anchor:"filteranchor"), class: "btn btn-filters"%>
  <%= link_to "Ascending prices", characters_path(asc: true, anchor:"filteranchor"), class: "btn btn-filters" %>
  <%= link_to "Descending prices", characters_path(desc: true, anchor:"filteranchor"), class: "btn btn-filters"%>
</div>

<div class="content">

  <div class="cards-container">
    <% if @characters.any? %>
      <ul>
        <% @characters.each do |character| %>
          <li class="card">
            <%= link_to character_path(character), class: 'card-link' do %>
              <div class="card">
                <% if character.photo.attached? %>
                  <%= cl_image_tag character.photo.key, alt: "text" %>
                <% else %>
                  <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg", alt: character.name, class: 'card-img'  %>
                <% end %>
                <div class="card-info">
                  <h3><%= character.name %></h3>
                  <p><%= character.univers %></p>
                  <p class="price">$<%= character.price %>/day</p>
                  <p class="price">
                    <i class="fa-solid fa-square-poll-vertical"></i>
                    <%= character.rating %>
                  </p>
                </div>
              </div>
            <% end %>
          <% end %>
        </li>
      </ul>
    <% else %>
      <p class="text-center"><%= "Sorry, '#{params[:query]}' is not available" %> <i class="fa-regular fa-face-sad-cry"></i></p>
    <% end %>

    <% if @reviews.any? %>
      <div class="col m-5 border rounded-4 p-4 shadow">
        <p><strong><i class="fa-solid fa-quote-left"></i> Some reviews :</strong></p>
        <% @reviews.each_with_index do |review, index| %>
          <div class="d-flex m-3 <%= @reviews.length == index + 1 ? '' : 'border-bottom' %>">
            <div class="mx-3 align-center">
              <% if review.character.user.photo.attached? %>
                <%= cl_image_tag review.character.user.photo.key, alt: "text", height: 50, width: 50, class: "rounded-circle object-fit-cover" %>
              <% else %>
                  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" alt="<%= review.character[:name] %>">
              <% end %>
            </div>
            <div>
              <%= review.user.first_name %> <i class="fa-solid fa-thumbs-<%= review.reco ? 'up' : 'down' %>"></i> <strong><%= link_to review.character.name, character_path(review.character) %></strong>:<br>
              <em>"<%= review.content %>"</em>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <% unless params[:query].present? %>
    <div class="map-container">
      <div class="map"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  <% end %>

</div>

app/views/characters/mychars.html.erb
<div class="container">
    <h1>My Characters</h1>
      <% if @characters.any? %>
    <ul>
        <% @characters.each do |character| %>
          <li class="card m-2">
            <%= link_to character_path(character), class: 'card-link' do %>
              <div class="card">
                  <% if character.photo.attached? %>
                    <%= cl_image_tag character.photo.key, alt: "text" %>
                  <% else %>
                      <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" alt="<%= character[:name] %>">
                  <% end %>
                  <div class="card-info">
                      <h3><%= character.name %></h3>
                      <p><%= character.univers %></p>
                      <p class="price"><%= character.price %>$/day</p>
                      <p class="price"><i class="fa-solid fa-square-poll-vertical"></i>
                      <% note = 0 %>
                      <% character.reviews.each do |review| %>
                        <% if review.reco == true %>
                          <% note += 1 %>
                        <% else %>
                          <% note -= 1 %>
                        <% end %>
                      <% end %>
                      <%= note %>
                      </p>
                  </div>
              </div>
            <% end %>
          <% end %>
          <% else %>
          <div class="container" style="height: 60vh;">
            <%= render "shared/modal" %>
            <p class="d-flex justify-content-center align-items-center" style="height: 60vh;">Sorry, you don't have any character <i class="fa-regular fa-face-sad-cry"></i></p>
            <%= link_to "Please add a character", '#', {:remote => true, 'data-bs-toggle' =>  "modal", 'data-bs-target' => '#addcharacter', class: "btn btn-ghost btn-ghost:hover d-flex justify-content-center align-items-center"} %>
          </div>
        <% end %>
      </li>
    </ul>


  </div>

app/views/characters/new.html.erb
<div class="col-4 mx-auto">
      <div class="mb-5">
        <h1>Add a character</h1>
      </div>
      <%= render "form", character: @character %>
</div>

app/views/characters/show.html.erb
<div class="container">
  <div class="m-5">
    <div class="col">
      <%= link_to "Back to list", characters_path, class: "btn btn-ghost mb-3" %>
        <h1><%= @character.name  %></h1>

      <div class="d-flex">
        <div class="d-flex col m-5 border rounded-4 p-4 shadow">
            <div class="card big_img">
              <% if @character.photo.attached? == true %>
                <%= cl_image_tag @character.photo.key, alt: "text" %>
              <% else %>
                <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" alt="<%= @character[:name] %>">
              <% end %>
            </div>

            <div class="d-flex ms-4 mt-3 align-items-center">
                <div class="mt-25">
                  <p><strong>from <%= @character.univers %></strong></p>
                  <p><i class="fa-solid fa-location-dot"></i> <%= @character.location %></p>
                  <p><i class="fa-solid fa-money-bill-wave"></i> <%= @character.price %> dollars / day</p>
                  <p><i class="fa-solid fa-brain"></i> <%= @character.skills %></p>
                </div>
            </div>
          </div>

          <% if @character.user != current_user %>
            <div class="col-4 m-5 border rounded-4 p-4 shadow">
              <%= render "/bookings/form", booking: Booking.new, character: @character %>
            </div>
          <% end %>
      </div>
    </div>
  </div>

  <div class="col-9 mx-auto mb-3">
    <%= render "characters/modal", review: @review, open: @review_modal_open %>
      <% if @character.user == current_user %>
        <div class="d-flex justify-content-between"><%= link_to "Edit your character", '#', {:remote => true, 'data-bs-toggle' =>  "modal", 'data-bs-target' => '#editcharacter', class: "col-6 btn btn-large"} %>
          <%= link_to 'Delete', character_path(@character),
          data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "col-3 btn btn-ghost btn-ghost:hover" %>
        </div>
      <% else %>
        <div class="d-flex justify-content-center">
        <%= link_to "Add review", '#', {:remote => true, 'data-bs-toggle' =>  "modal", 'data-bs-target' => '#addreview', class: "btn btn-large btn-large:hover"} %>
        </div>
      <% end %>
  </div>

  <div class="col m-5 border rounded-4 p-4 shadow">
    <p><strong>Reviews </strong><i class="fa-solid fa-star"></i></p>
    <% if @character.reviews.any? %>
      <% @character.reviews.each_with_index do |review, index| %>
        <div class="d-flex m-2 my-3 <%= @character.reviews.length == index + 1 ? '' : 'border-bottom' %>">
          <div class="mx-3 align-center">
            <% if review.character.user.photo.attached? %>
              <%= cl_image_tag review.character.user.photo.key, alt: "text", height: 50, width: 50, class: "rounded-circle object-fit-cover" %>
            <% else %>
                <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" alt="<%= review.character[:name] %>">
            <% end %>
          </div>
          <div>
            <% if review.reco == true %>
              <p><strong><%= review.user.first_name %> <i class="fa-solid fa-thumbs-up"></i><br></strong>
            <% else %>
              <p><strong><%= review.user.first_name %> <i class="fa-solid fa-thumbs-down"></i><br></strong>
            <% end %>
            "<%= review.content %>"</p>
          </div>
        </div>
      <% end %>
    <% else %>
        <p>No reviews yet</p>
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentMyHero</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.png' %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>
  <body data-controller="anchor-scroll">
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/new.html.erb
<%= render 'form', review: @review, user: @user, character: @character %>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <%= render "shared/modal" %>
<% end %>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="container-fluid mx-3">
    <%= link_to "/characters", class: "navbar-brand" do %>
      <%= image_tag("logo.svg",
      width: 50, height: 50, crop: :fill) %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.photo.attached? %>
                <%= cl_image_tag current_user.photo.key, alt: "avatar", height: 50, width: 50, class: "rounded-circle object-fit-cover"   %>
              <% else %>
                  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" alt="avatar", height= 50, width= 50, class= "rounded-circle object-fit-cover">
              <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My bookings", dashboard_path, class: "dropdown-item" %>
              <%= link_to "My characters", mychars_path, class: "dropdown-item" %>
              <%= link_to "Add a character", '#', {:remote => true, 'data-bs-toggle' =>  "modal", 'data-bs-target' => '#addcharacter', class: "dropdown-item"} %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>